/*
 * generated by Xtext 2.12.0
 */
package nl.utwente.fmt.ras.ui.quickfix

import org.eclipse.xtext.xbase.ui.quickfix.XbaseQuickfixProvider

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
class RasQuickfixProv