/*
 * generated by Xtext 2.12.0
 */
package nl.utwente.fmt.ras.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.ecl